# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://jadcourbage.github.io/
title: Nawalishop - Comment supprimer son compte ?
email: nawalishop.app@gmail.com
author: Jad Courbage
description: > # "Write an awesome description for your new site here. 
  Comment supprimer son compte ?
copyright: ''
credits: ''

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

